### ISSUE TITLE
Does not work when not listed on top of the package list

### ISSUE THREAD

**Issue by msavin** [dburles/mongo-collection-instances#16]
Hey David,

Big fans of your work with this package. We're using it with Mongol, and its been great to have the package automatically configure itself. However, for some users it does not work if the package is not listen on top. I'm wondering if you know of any ways to resolve this issue?
 
https://github.com/msavin/Mongol/issues/30#issuecomment-76362753

**Comment by dburles** [comment]
Hey thanks @msavin. I've just become aware of the problem myself and have just begun looking into a potential solution beyond the one you described, but for now I'd recommend it as a workaround until we have a better solution.

**Comment by dburles** [comment]
On a side note it might be worth updating the dependency to `0.3.3` as I've recently merged some changes from @rclai that solve a couple of issues, see https://github.com/dburles/mongo-collection-instances/pull/14

**Comment by msavin** [comment]
Thanks for letting me know.

I submitted an issue to MDG, maybe we can get some kind of standard support for it.
https://github.com/meteor/meteor/issues/3827
