### ISSUE TITLE
Client side only

### ISSUE THREAD

**Issue by msavin** [dburles/mongo-collection-instances#17]
Hey, are you able to create a version of this package that only works on the client? That way, there wouldn't be potential issues with other packages on the server side, and I'd guess/hope that it would still work fine for detecting collections on the client.

**Comment by dburles** [comment]
Hey what kind of issues on the server? are they related to the load order issue? https://github.com/dburles/mongo-collection-instances/issues/16

**Comment by msavin** [comment]
Here are a few that may be conflicting with the package: 

https://github.com/msavin/Mongol/issues/49
https://github.com/msavin/Mongol/issues/48
https://github.com/msavin/Mongol/issues/43

Our plan is to let the user custom set the collection names with a session variable, or use your package to auto- detect. But we wouldn't want it to run on the server in either way. 




On Mar 11, 2015, at 06:17 PM, David Burles <notifications@github.com> wrote:

Hey what kind of issues on the server? are they related to the load order issue? #16

**Comment by dburles** [comment]
update your dependancy to 0.3.3 and hopefullt it should resolve those issues

**Comment by msavin** [comment]
Thanks I'll keep ya posted. 

On Mar 11, 2015, at 06:26 PM, David Burles <notifications@github.com> wrote:

update your dependancy to 0.3.3 and hopefullt it should resolve those issues

**Comment by dburles** [comment]
Great
