### ISSUE TITLE
getAll broken?

### ISSUE THREAD

**Issue by SachaG** [dburles/mongo-collection-instances#21]
I'm getting an error when trying to use getAll:

```
Object function (name, options) {...} has no method 'getAll'
```

**Comment by dburles** [comment]
Interesting. The only thing I can think of is that it's gone to an earlier version of the package before I added that message. Try confirm that you're on the latest

**Comment by SachaG** [comment]
You're right, Meteor had "helpfully" decided to pick version 0.1.3 for me…
