### ISSUE TITLE
  Meteor.addCollectionExtension deprecation

### ISSUE THREAD

**Issue by patrickml** [dburles/mongo-collection-instances#26]
this has been deprecated and replaced with `CollectionExtensions.addPrototype` until this changes we all will keep receiving warn messages

**Comment by rclai** [comment]
Closable.

**Comment by patrickml** [comment]
Why is this closeable? `CollectionExtensions.addExtension` is still being used https://github.com/dburles/mongo-collection-instances/blob/master/mongo-instances.js#L3

**Comment by rclai** [comment]
Right, that's the new API.

**Comment by rclai** [comment]
The package just got updated.

**Comment by patrickml** [comment]
ahhhhh sorry, I guess i've been seen the error message so many time that i got confused
